# Generated by Django 2.0.6 on 2018-06-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('pub_date', models.CharField(max_length=20)),
                ('body', models.CharField(max_length=2000)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
